# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

skip_docs

default_platform(:android)

platform :android do
  desc 'adding tag and upload to Play Store'
  lane :play_store do |options|
    release_to_play_store
  end
end

def release_to_play_store
  upload_to_play_store(
      track: 'production',
      apk: 'app/build/outputs/apk/release/app-release.apk'
  )
end